# Generated by Django 4.2.15 on 2025-02-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0017_remove_profile_uploads_profile_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='embedding',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
