# Generated by Django 4.2.15 on 2024-09-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0013_dataset_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avater',
            field=models.ImageField(default='dr_strange.jpg', null=True, upload_to=''),
        ),
    ]
