# Generated by Django 4.2.15 on 2025-02-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0015_remove_dataset_path_alter_dataset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uploads',
            field=models.ManyToManyField(related_name='uploads', to='foto.dataset'),
        ),
    ]
