# Generated by Django 4.2.15 on 2025-02-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0018_profile_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='embedding',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
