# Generated by Django 4.2.15 on 2025-02-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0020_remove_profile_uploads_profile_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='target_img')),
                ('user', models.ManyToManyField(blank=True, to='foto.profile')),
            ],
        ),
    ]
