# Generated by Django 4.2.15 on 2025-02-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0021_user_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='embedding',
        ),
    ]
